import Link from "next/link";
import { AlertOctagon, ArrowRight, Bot, CalendarClock, Check, CheckCircle2, CircleDot, ClipboardCheck, FileDiff, ListChecks, PackageCheck, Scale, ScrollText, UserRound } from "lucide-react";
import { agentApi } from "@/lib/api/agent";
import { phaseApi } from "@/lib/api/phase2";
import { projectApi } from "@/lib/api/projects";
import { DEMO_NOW, formatDeadlineRemaining } from "@/lib/product-context";
import { RiskBadge } from "@/components/ui/badges";

const stages = ["文件解析", "要求确认", "证据匹配", "合规审查", "整改", "文件封装", "提交准备"];

export default async function ProjectOverviewPage({ params }: { params: Promise<{ projectId: string }> }) {
  const { projectId } = await params;
  const [project, requirements, disqualifications, matches, consistency, tasks, packageResult, audit, agentResult] = await Promise.all([projectApi.get(projectId), projectApi.requirements(projectId), projectApi.disqualifications(projectId), phaseApi.evidenceMatches(projectId), phaseApi.consistency(projectId), phaseApi.tasks(projectId), phaseApi.package(projectId), phaseApi.audit(projectId), agentApi.getRun(projectId)]);
  const source = agentResult.source === "failure" ? "error" : agentResult.source;
  const currentStage = Math.max(0, stages.findIndex((stage) => project.stage.includes(stage.replace("合规审查", "合规"))));
  const openTasks = tasks.data.filter((item) => item.status !== "done").sort((a, b) => a.dueDate.localeCompare(b.dueDate));
  const openConsistency = consistency.data.filter((item) => item.status === "open" || item.status === "review");
  const failedChecks = packageResult.data.checks.filter((item) => item.status === "failed");
  const pendingMatches = matches.data.flatMap((item) => item.candidates).filter((item) => item.decision === "pending");
  const reviewCount = requirements.filter((item) => item.status === "review" || item.confidence < .7).length;
  const now = source === "demo" ? DEMO_NOW : new Date();
  return <div className="page"><header className="page-header"><div className="page-title-group"><span className="project-code">{project.projectCode}</span><h1>{project.name}</h1><p>{project.buyerName} · <span className={`data-source ${source}`}>{source === "api" ? "API 聚合" : source === "demo" ? "确定性演示" : "Agent API 失败"}</span></p></div><div className="header-actions"><Link className="button" href={`/agent?project=${projectId}`}><Bot size={15} />打开 Agent</Link><Link className="button" href={`/projects/${projectId}/review`}><ClipboardCheck size={15} />最终复核</Link><Link className="button" href={`/projects/${projectId}/responses`}><FileDiff size={15} />要求与响应</Link><Link className="button primary" href={`/projects/${projectId}/requirements`}>复核招标要求<ArrowRight size={15} /></Link></div></header>
    {agentResult.source === "failure" && <div className="mutation-feedback error" role="alert"><AlertOctagon size={16} /><span><strong>Agent 聚合失败</strong><small>{agentResult.error.message} 未自动切换为演示结果。</small></span></div>}
    <section className="panel stage-panel" aria-label="项目阶段"><div className="stage-heading"><span><strong>当前阶段：{project.stage}</strong><small>{reviewCount} 项要求仍需人工复核</small></span><span>整体完成度 <strong>{project.progress}%</strong></span></div><ol className="stage-stepper">{stages.map((stage, index) => <li key={stage} className={index < currentStage ? "done" : index === currentStage ? "current" : ""}><span>{index < currentStage ? <Check size={13} /> : index + 1}</span><strong>{stage}</strong><small>{index < currentStage ? "已完成" : index === currentStage ? "进行中" : "待开始"}</small></li>)}</ol></section>
    <section className="overview-metrics" aria-label="合规概况"><OverviewMetric label="总要求" value={requirements.length} note={`${reviewCount} 项需人工复核`} icon={<ListChecks size={16} />} /><OverviewMetric label="否决项" value={disqualifications.filter((item) => item.status !== "resolved" && item.status !== "waived").length} note={`${disqualifications.filter((item) => item.status === "rule_hit").length} 项规则命中`} icon={<AlertOctagon size={16} />} tone="fatal" /><OverviewMetric label="已满足" value={requirements.filter((item) => item.status === "met").length} note="基于当前要求状态" icon={<CheckCircle2 size={16} />} tone="success" /><OverviewMetric label="缺少证据" value={requirements.filter((item) => item.status === "missing").length} note={`${pendingMatches.length} 个候选待决定`} icon={<CircleDot size={16} />} tone="warning" /><OverviewMetric label="文件冲突" value={openConsistency.length} note="未解决或待复核" icon={<FileDiff size={16} />} tone="warning" /><OverviewMetric label="待整改" value={openTasks.length} note="未完成任务" icon={<ClipboardCheck size={16} />} /></section>
    <div className="overview-grid"><section className="panel workflow-panel"><div className="panel-header"><div><h2>合规交付工作流</h2><p>从各工作台聚合当前处理状态</p></div></div><div className="workflow-links"><Workflow href={`/projects/${projectId}/evidence-matching`} icon={<Scale size={16} />} title="证据匹配" detail="候选需人工确认" value={`${pendingMatches.length} 个待决定`} /><Workflow href={`/projects/${projectId}/consistency`} icon={<FileDiff size={16} />} title="一致性检查" detail="金额、主体、日期与承诺" value={`${openConsistency.length} 个未解决`} danger={openConsistency.length > 0} /><Workflow href={`/projects/${projectId}/tasks`} icon={<ClipboardCheck size={16} />} title="整改任务" detail="责任人和截止时间" value={`${openTasks.length} 个未完成`} /><Workflow href={`/projects/${projectId}/package`} icon={<PackageCheck size={16} />} title="文件封装" detail="确定性目录与规则校验" value={`${failedChecks.length} 个阻塞`} danger={failedChecks.length > 0} /><Workflow href={`/projects/${projectId}/audit`} icon={<ScrollText size={16} />} title="审计记录" detail="模型、规则与人工操作" value={`${audit.data.length} 条事件`} /></div></section>
      <section className="panel risk-focus"><div className="panel-header"><div><h2>最高优先级风险</h2><p>从否决项状态动态排序</p></div><Link href={`/projects/${projectId}/disqualifications`}>查看全部 <ArrowRight size={13} /></Link></div><div className="risk-list">{disqualifications.filter((item) => item.status !== "resolved" && item.status !== "waived").slice(0, 3).map((item) => <RiskRow key={item.id} title={item.title} source={`${item.source} · 第 ${item.page} 页`} owner={item.owner} due={item.dueDate} review={item.status === "candidate"} />)}</div></section>
      <section className="panel deadline-card"><div className="panel-header"><div><h2>关键时间</h2><p>以项目截止时间与未完成任务为准</p></div><CalendarClock size={18} /></div><div className="countdown-block"><span>距离投标截止</span><strong>{formatDeadlineRemaining(project.deadline, now)}</strong><small>{project.deadline} · Asia/Shanghai</small></div><div className="milestone-list">{openTasks.slice(0, 3).map((task) => <p key={task.id}><span>{task.dueDate.slice(5)}</span><strong>{task.title}</strong><em>{task.owner}</em></p>)}</div></section>
      <section className="panel activity-panel"><div className="panel-header"><div><h2>最近活动</h2><p>追加式审计记录</p></div><span className="audit-label">{audit.source === "api" ? "API" : "确定性演示"}</span></div><ol className="activity-list">{audit.data.slice(0, 4).map((item) => <Activity key={item.id} name={item.actor} text={item.action} time={item.timestamp.slice(11, 16)} system={item.actorType !== "human"} />)}</ol></section>
      <section className="panel owners-panel"><div className="panel-header"><div><h2>责任人与阻塞任务</h2><p>按截止时间展示未完成任务</p></div><UserRound size={17} /></div><div className="owner-list">{openTasks.slice(0, 3).map((task) => <p key={task.id}><span className="avatar">{task.owner.slice(0, 1)}</span><span><strong>{task.owner}</strong><small>{task.title}</small></span><em>{task.dueDate.slice(5)}</em></p>)}</div></section></div>
  </div>;
}

function OverviewMetric({ label, value, note, icon, tone = "" }: { label: string; value: number; note: string; icon: React.ReactNode; tone?: string }) { return <article className={`overview-metric ${tone}`}><span>{icon}</span><div><small>{label}</small><strong>{value}</strong><p>{note}</p></div></article>; }
function Workflow({ href, icon, title, detail, value, danger = false }: { href: string; icon: React.ReactNode; title: string; detail: string; value: string; danger?: boolean }) { return <Link href={href}>{icon}<span><strong>{title}</strong><small>{detail}</small></span><em className={danger ? "danger-text" : ""}>{value}</em><ArrowRight size={13} /></Link>; }
function RiskRow({ title, source, owner, due, review = false }: { title: string; source: string; owner: string; due: string; review?: boolean }) { return <article><RiskBadge level={review ? "high" : "fatal"} /><div><strong>{title}</strong><small>{source}</small></div><span><small>负责人</small>{owner}</span><span><small>截止</small>{due}</span></article>; }
function Activity({ name, text, time, system = false }: { name: string; text: string; time: string; system?: boolean }) { return <li><span className={system ? "activity-dot system" : "activity-dot"} /><div><strong>{name}</strong><p>{text}</p></div><time>{time}</time></li>; }
