"use client";

import { useMemo, useState } from "react";
import { AlertTriangle, CalendarClock, CheckCircle2, ChevronRight, Clock3, Download, FileSearch, FileText, Folder, History, Search, ShieldAlert, Tag, Upload, UsersRound, XCircle } from "lucide-react";
import { ConfidenceIndicator } from "@/components/ui/badges";
import type { DataSource, EvidenceAsset } from "@/lib/phase-data/types";

const statusLabel = { verified: "已人工验证", review: "待人工验证", expired: "已过期", conflict: "存在冲突" };

export function EvidenceLibrary({ initialAssets, source }: { initialAssets: EvidenceAsset[]; source: DataSource }) {
  const [assets, setAssets] = useState(initialAssets);
  const [selectedId, setSelectedId] = useState(initialAssets[0]?.id);
  const [query, setQuery] = useState("");
  const [type, setType] = useState("all");
  const [status, setStatus] = useState("all");
  const [tab, setTab] = useState<"preview" | "claims" | "usage" | "history">("claims");
  const selected = assets.find((item) => item.id === selectedId) ?? assets[0];
  const filtered = useMemo(() => assets.filter((item) => `${item.name}${item.tags.join("")}${item.legalEntity}`.toLowerCase().includes(query.toLowerCase()) && (type === "all" || item.type === type) && (status === "all" || item.status === status)), [assets, query, status, type]);
  const types = Array.from(new Set(assets.map((item) => item.type)));

  function addFiles(files: FileList | null) {
    if (!files?.length) return;
    const uploaded = Array.from(files).map((file, index): EvidenceAsset => ({ id: `local-${Date.now()}-${index}`, name: file.name, type: "待分类", legalEntity: "主体待确认", status: "review", validUntil: "待提取", expiryDays: 0, claimCount: 0, usageCount: 0, owner: "刘敏", department: "待分配", lastReviewed: "未复核", tags: ["本地上传"], pageCount: 0, size: `${(file.size / 1024 / 1024).toFixed(1)} MB`, version: "V1", claims: [], usedBy: [] }));
    setAssets((current) => [...uploaded, ...current]); setSelectedId(uploaded[0].id);
  }

  function exportInventory() {
    const rows = [["材料名称", "类型", "主体", "状态", "有效期", "负责人"], ...filtered.map((item) => [item.name, item.type, item.legalEntity, statusLabel[item.status], item.validUntil, item.owner])];
    const url = URL.createObjectURL(new Blob([`\uFEFF${rows.map((row) => row.join(",")).join("\n")}`], { type: "text/csv;charset=utf-8" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "企业材料清单.csv"; anchor.click(); URL.revokeObjectURL(url);
  }

  if (!selected) return null;
  return <div className="page evidence-page">
    <header className="page-header"><div className="page-title-group"><h1>企业材料库</h1><p>将证书、主体、人员与项目案例维护为可复用、可验证的企业证据。</p></div><div className="header-actions"><span className={`data-source ${source}`}>{source === "api" ? "API 数据" : "本地演示数据"}</span><button className="button" type="button" onClick={exportInventory}><Download size={14} />导出清单</button><label className="button primary"><Upload size={14} />上传材料<input className="sr-only" type="file" multiple onChange={(event) => addFiles(event.target.files)} /></label></div></header>
    <section className="evidence-alerts" aria-label="材料提醒"><EvidenceAlert icon={<CalendarClock />} value="1" label="30 天内到期" tone="danger" onClick={() => setStatus("expired")} /><EvidenceAlert icon={<Clock3 />} value="2" label="90 天内到期" onClick={() => setStatus("review")} /><EvidenceAlert icon={<UsersRound />} value="1" label="缺少主体" onClick={() => setQuery("主体待确认")} /><EvidenceAlert icon={<FileSearch />} value="2" label="未经人工验证" onClick={() => setStatus("review")} /><EvidenceAlert icon={<ShieldAlert />} value="2" label="存在冲突" tone="danger" onClick={() => setStatus("conflict")} /><EvidenceAlert icon={<History />} value="1" label="长期未复核" onClick={() => setQuery("案例合同B")} /></section>
    <div className="evidence-layout">
      <aside className="panel evidence-sidebar"><h2>材料范围</h2><label className="evidence-search"><Search size={14} /><input aria-label="搜索企业材料" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜索文件、标签、主体" /></label><section><h3><Folder size={13} />材料类型</h3><button className={type === "all" ? "active" : ""} type="button" onClick={() => setType("all")}><span>全部材料</span><em>{assets.length}</em></button>{types.map((item) => <button key={item} className={type === item ? "active" : ""} type="button" onClick={() => setType(item)}><span>{item}</span><em>{assets.filter((asset) => asset.type === item).length}</em></button>)}</section><section><h3><Tag size={13} />状态</h3>{Object.entries(statusLabel).map(([key, label]) => <button key={key} className={status === key ? "active" : ""} type="button" onClick={() => setStatus(status === key ? "all" : key)}><span>{label}</span><em>{assets.filter((asset) => asset.status === key).length}</em></button>)}</section>{(query || type !== "all" || status !== "all") && <button className="button small full-width" type="button" onClick={() => { setQuery(""); setType("all"); setStatus("all"); }}>清除筛选</button>}</aside>
      <section className="panel evidence-list-panel"><div className="panel-header"><div><h2>材料清单</h2><p>{filtered.length} 份材料 · {filtered.reduce((sum, item) => sum + item.claimCount, 0)} 个可引用 Claim</p></div><span>最后同步 14:30</span></div><div className="evidence-table-wrap"><table className="evidence-table"><thead><tr><th>材料</th><th>主体 / 部门</th><th>有效期</th><th>状态</th><th>使用</th><th>负责人</th></tr></thead><tbody>{filtered.map((asset) => <tr key={asset.id} className={asset.id === selected.id ? "selected" : ""} onClick={() => setSelectedId(asset.id)}><td><span className="asset-icon"><FileText size={15} /></span><span><strong>{asset.name}</strong><small>{asset.type} · {asset.version} · {asset.size}</small></span></td><td><strong>{asset.legalEntity}</strong><small>{asset.department}</small></td><td><strong>{asset.validUntil}</strong><small className={asset.expiryDays < 0 ? "danger-text" : ""}>{asset.expiryDays < 0 ? `已过期 ${Math.abs(asset.expiryDays)} 天` : asset.expiryDays < 90 ? `${asset.expiryDays} 天后到期` : "有效"}</small></td><td><span className={`asset-status ${asset.status}`}>{asset.status === "verified" ? <CheckCircle2 size={11} /> : asset.status === "expired" || asset.status === "conflict" ? <XCircle size={11} /> : <AlertTriangle size={11} />}{statusLabel[asset.status]}</span></td><td><strong>{asset.usageCount} 个项目</strong><small>{asset.claimCount} 个 Claim</small></td><td><strong>{asset.owner}</strong><small>{asset.lastReviewed}</small></td></tr>)}</tbody></table>{filtered.length === 0 && <div className="empty-state"><strong>没有匹配的企业材料</strong>调整范围或上传新材料。</div>}</div></section>
      <aside className="panel evidence-detail"><div className="evidence-detail-head"><span className="asset-icon large"><FileText size={20} /></span><div><strong>{selected.name}</strong><small>{selected.version} · {selected.pageCount} 页 · {selected.size}</small></div><span className={`asset-status ${selected.status}`}>{statusLabel[selected.status]}</span></div><div className="detail-tabs evidence-tabs" role="tablist">{([['preview','预览'],['claims','Claims'],['usage','使用项目'],['history','版本']] as const).map(([key, label]) => <button key={key} className={tab === key ? "active" : ""} role="tab" aria-selected={tab === key} type="button" onClick={() => setTab(key)}>{label}{key === "claims" && <span>{selected.claims.length}</span>}</button>)}</div><div className="evidence-detail-body">{tab === "claims" && <div className="claims-list"><div className="claims-summary"><strong>{selected.claims.length} 个结构化 Claim</strong><small>每项均保留来源页与置信度</small></div>{selected.claims.map((claim) => <article key={claim.id} className={claim.conflict ? "conflict" : ""}><div><span>{claim.label}</span><strong>{claim.value}</strong></div><p>可证明：{claim.proves}</p><footer><button type="button" onClick={() => window.alert(`已定位 ${selected.name} 第 ${claim.page} 页。`)}>第 {claim.page} 页 <ChevronRight size={11} /></button><ConfidenceIndicator value={claim.confidence} /></footer>{claim.conflict && <aside><AlertTriangle size={12} />{claim.conflict}</aside>}</article>)}{selected.claims.length === 0 && <div className="empty-state"><strong>尚未抽取 Claim</strong>本地上传材料需连接后端解析后抽取。</div>}</div>}{tab === "preview" && <div className="evidence-preview"><div><span>{selected.legalEntity}</span><strong>{selected.name}</strong><p>此处为确定性文档预览模拟。正式接入后按页渲染并显示 Claim 定位框。</p><small>第 1 页 / 共 {selected.pageCount || "?"} 页</small></div></div>}{tab === "usage" && <div className="usage-list"><h3>已关联项目</h3>{selected.usedBy.map((project) => <p key={project}><span><strong>{project}</strong><small>证据引用正在使用</small></span><ChevronRight size={13} /></p>)}{!selected.usedBy.length && <div className="empty-state"><strong>尚未被项目使用</strong>可在证据匹配工作台建立关联。</div>}</div>}{tab === "history" && <div className="version-list"><h3>版本历史</h3><p><span>{selected.version}</span><strong>当前版本</strong><small>{selected.lastReviewed} · {selected.owner} 复核</small></p><p><span>V1</span><strong>初始上传</strong><small>保留原始文件哈希</small></p></div>}</div></aside>
    </div>
  </div>;
}

function EvidenceAlert({ icon, value, label, tone = "", onClick }: { icon: React.ReactNode; value: string; label: string; tone?: string; onClick: () => void }) { return <button className={tone} type="button" onClick={onClick}><span>{icon}</span><strong>{value}</strong><small>{label}</small><ChevronRight size={13} /></button>; }
